import * as React from "react";
import AppBar from "@mui/material/AppBar";
import Box from "@mui/material/Box";
import Toolbar from "@mui/material/Toolbar";
import Typography from "@mui/material/Typography";
import IconButton from "@mui/material/IconButton";
import InfoIcon from "@mui/icons-material/Info";
import Alert from "@mui/material/Alert";
import AlertTitle from "@mui/material/AlertTitle";
import Modal from "@mui/material/Modal";
import WarningAmberIcon from "@mui/icons-material/WarningAmber";

const style = {
  position: "absolute",
  top: "50%",
  left: "50%",
  transform: "translate(-50%, -50%)",
  width: 400,
  height: 400,
  bgcolor: "background.paper",
  border: "1px solid #000",
  boxShadow: 24,
  p: 4,
  borderRadius: 5,
};

export default function Header() {
  const [open, setOpen] = React.useState(false);
  const handleOpen = () => setOpen(true);
  const handleClose = () => setOpen(false);
  return (
    <>
      <Box sx={{ flexGrow: 1 }} marginBottom="0px">
        <AppBar position="static">
          <Toolbar>
            <Typography
              variant="h4"
              component="div"
              align="center"
              sx={{ flexGrow: 1, marginLeft: "3rem" }}
            >
              AI Fitness Coach
            </Typography>
            <IconButton
              size="large"
              edge="start"
              color="inherit"
              aria-label="open drawer"
              sx={{ mr: 2 }}
              onClick={handleOpen}
            >
              <InfoIcon />
            </IconButton>
            <Modal
              open={open}
              onClose={handleClose}
              aria-labelledby="modal-modal-title"
              aria-describedby="modal-modal-description"
            >
              <Box sx={style}>
                <Typography id="modal-modal-title" variant="h4" component="h2">
                  Disclaimer
                </Typography>
                <Typography sx={{ mt: 2 }}>
                  The program plan is generated by a Machine Learning Language
                  Model developed by OpenAI. Some of the generated information
                  might not be 100% accurate and should be followed at the
                  discretion of the user.
                </Typography>
                <Typography sx={{ mt: 2 }}>
                  This app is meant for beginners who are new to fitness and are
                  quickly able to generate a daily fitness plan personalized to
                  their needs.
                </Typography>
              </Box>
            </Modal>
          </Toolbar>
        </AppBar>
      </Box>
      <Box
        sx={{
          width: "50%",
          margin: "0 auto",
          padding: "12px",
        }}
      >
        <Typography
          variant="h6"
          component="div"
          align="center"
          sx={{ flexGrow: 1 }}
        >
          {/* AI Fitness Coach is an application which generates a fitness plan
          based on user inputs. To generate a plan, select a workout and click
          "Generate Plan". To achieve the most personalized result, enter user
          information in the personalize section. */}
          Select your workout of choice and optimize it with your personalized
          plan.
        </Typography>
      </Box>
    </>
  );
}